WITH BASE_INTEGRATION AS ( 

    SELECT 
        CM.NUMERO_CONTRATO AS CONTRATO
        ,SPLIT_PART(CM.RAZON_SOCIAL, ',', 1) AS PROVEEDOR
        ,IV.FACTURA
        ,IV.UUID
        ,CM.NUMERO_ORDEN_SUMINISTRO
        ,PRECIO_UNITARIO * CANTIDAD_SOLICITADA AS IMPORTE
        ,PN.PENA AS IMPORTE_SANCION
        ,null AS IMPORTE_DEDUCTIVA
        ,CASE 
            
            WHEN CM.NUMERO_CONTRATO IN ('LA-E115-2022-MED-INSABI-188-2023/2024', 'LA-E115-2022-MED-INSABI-122-2023/2024') THEN 'FONDO'
            WHEN CM.NUMERO_CONTRATO ILIKE 'LA-E115-2022-MED-INSABI-034-2023/2024' THEN 'PEF'
            ELSE CM.NUMERO_CONTRATO
            END
            AS FINANCIAMIENTO
        ,2023 AS FECHA_CONTRATO
        ,PN.OFICIO AS CEDULA
        ,CM.DESCRIPCION_ESTATUS_ORDEN_SUMINISTRO
        ,SG.ESTADO_DE_LA_FACTURA
        ,PM.IMPORTE AS IMPORTE_PAGADO
    FROM {{ref('stg_camunda')}} CM
    LEFT JOIN {{ref('stg_imssb_invoices')}} IV
        ON CM.NUMERO_ORDEN_SUMINISTRO = IV.ORDEN_DE_SUMINISTRO
    LEFT JOIN {{ref('stg_sagi')}}  SG
        ON IV.UUID = SG.FOLIO_FISCAL
    LEFT JOIN {{ref('stg_imssb_penalties')}} PN
        ON CM.NUMERO_ORDEN_SUMINISTRO = PN.ORDEN_DE_SUMINISTRO
    LEFT JOIN {{ref('stg_imsb_payments')}}  PM
        ON IV.UUID = PM.FOLIO_FISCAL
)

, CURATED_INTEGRATION AS ( 
    SELECT 
        CONTRATO
        ,PROVEEDOR
        ,FACTURA
        ,UUID
        ,NUMERO_ORDEN_SUMINISTRO
        ,IMPORTE
        ,IMPORTE_SANCION
        ,IMPORTE_DEDUCTIVA
        ,FINANCIAMIENTO
        ,FECHA_CONTRATO
        ,CEDULA
        ,DESCRIPCION_ESTATUS_ORDEN_SUMINISTRO
        ,ESTADO_DE_LA_FACTURA
        ,IMPORTE_PAGADO
        ,CURRENT_TIMESTAMP() AS ETL_LOAD_DATE
    FROM BASE_INTEGRATION
    WHERE
        UUID IS NOT NULL
        AND IMPORTE_PAGADO IS NULL
        AND (ESTADO_DE_LA_FACTURA IS NOT NULL OR ESTADO_DE_LA_FACTURA  NOT ILIKE '%cancelad%')
    )

SELECT 
    CONTRATO
    ,PROVEEDOR
    ,FACTURA
    ,UUID
    ,NUMERO_ORDEN_SUMINISTRO
    ,IMPORTE
    ,IMPORTE_SANCION
    ,IMPORTE_DEDUCTIVA
    ,FINANCIAMIENTO
    ,FECHA_CONTRATO
    ,CEDULA
    ,DESCRIPCION_ESTATUS_ORDEN_SUMINISTRO
    ,ESTADO_DE_LA_FACTURA
    ,IMPORTE_PAGADO
    ,ETL_LOAD_DATE
FROM CURATED_INTEGRATION