WITH BASE_CAMUNDA AS ( 
    SELECT 
        *
        , CASE
            WHEN ETL_FILE_NAME LIKE '%fantasmas%' 
                THEN '2023-12-31 12:00:00'::timestamp
            ELSE 
                TO_TIMESTAMP(
                    SUBSTR(ETL_FILE_NAME, 
                           REGEXP_INSTR(ETL_FILE_NAME, '[0-9]{2}-[0-9]{2}-[0-9]{4}'), 
                           16), 
                    'DD-MM-YYYY HH24 MI'
                )
          END AS batch_date
    FROM {{ source('IMSS_BIENESTAR', 'CAMUNDA_ORDERS') }} 
) 

, 

LATEST_CAMUNDA AS ( 
SELECT 
    NUMERO_ORDEN_SUMINISTRO
    ,REGEXP_REPLACE(NUMERO_CONTRATO, '-(HJM|INER|HGM|HRAEPY|HEP|INCAN|HGEA)$', '') AS NUMERO_CONTRATO
    ,RFC_PROVEEDOR
    ,RAZON_SOCIAL
    ,CLAVE_MEDICAMENTO
    ,TRIM(MEDICAMENTO) AS MEDICAMENTO
    ,PRECIO_UNITARIO::NUMBER AS PRECIO_UNITARIO
    ,CANTIDAD_SOLICITADA
    ,TRIM(ALMACEN_ENTREGA) AS ALMACEN_ENTREGA
    ,TRIM(CLUES_DESTINO) AS CLUES_DESTINO
    ,ENTIDAD_DESTINO
    ,NOMBRE_UNIDAD
    ,DESCRIPCION_ESTATUS_ORDEN_SUMINISTRO
    ,COALESCE(
        TRY_TO_DATE(FECHA_AUTORIZACION, 'DD/MM/YYYY'), 
        TRY_TO_DATE(FECHA_AUTORIZACION, 'YYYY-MM-DD')
      ) AS FECHA_AUTORIZACION
    ,COALESCE(
        TRY_TO_DATE(FECHA_LIMITE_ENTREGA, 'DD/MM/YYYY'), 
        TRY_TO_DATE(FECHA_LIMITE_ENTREGA, 'YYYY-MM-DD')
      ) AS FECHA_LIMITE_ENTREGA
    ,NUMERO_PROCEDIMIENTO
    ,REPLACE(ORDEN_REMISION, '.0', '')::NUMBER AS ORDEN_REMISION
    ,ESTATUS
    ,BATCH_DATE
    ,CURRENT_TIMESTAMP() AS ETL_LOAD_DATE
FROM BASE_CAMUNDA
QUALIFY 
ROW_NUMBER() OVER(PARTITION BY NUMERO_ORDEN_SUMINISTRO ORDER BY BATCH_DATE DESC) = 1
)

SELECT
     NUMERO_ORDEN_SUMINISTRO
    ,NUMERO_CONTRATO
    ,RFC_PROVEEDOR
    ,RAZON_SOCIAL
    ,CLAVE_MEDICAMENTO
    ,MEDICAMENTO
    ,PRECIO_UNITARIO
    ,CANTIDAD_SOLICITADA
    ,ALMACEN_ENTREGA
    ,CLUES_DESTINO
    ,ENTIDAD_DESTINO
    ,NOMBRE_UNIDAD
    ,DESCRIPCION_ESTATUS_ORDEN_SUMINISTRO
    ,FECHA_AUTORIZACION
    ,FECHA_LIMITE_ENTREGA
    ,NUMERO_PROCEDIMIENTO
    ,ORDEN_REMISION
    ,ESTATUS
    ,BATCH_DATE
    ,ETL_LOAD_DATE
FROM LATEST_CAMUNDA
